AllCops:
    DisplayCopNames: true
    Exclude:
        - 'vendor/**/*'
Style/Documentation:
    Enabled: false
Style/AsciiComments:
    Enabled: false
Style/StringLiterals:
    Enabled: false
Style/NumericLiterals:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false
Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'
Layout/SpaceAroundEqualsInParameterDefault:
    EnforcedStyle: no_space
Layout/SpaceInsideHashLiteralBraces:
    EnforcedStyle: no_space