defaults: &defaults
  working_directory: ~/tsumamigui

version: 2
jobs:
  lint:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: gems-{{ checksum "Gemfile" }}
      - run: bundle install --path vendor/bundle
      - run: bundle exec rubocop
      - save_cache:
          paths:
            - vendor/bundle
          key: gems-{{ checksum "Gemfile" }}
    
  rspec-2_4_2:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: gems-{{ checksum "Gemfile" }}
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
      - save_cache:
          paths:
            - vendor/bundle
          key: gems-{{ checksum "Gemfile" }}


  rspec-2_3_5:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.3.5-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: gems-{{ checksum "Gemfile" }}-2_3_5
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
      - save_cache:
          paths:
            - vendor/bundle
          key: gems-{{ checksum "Gemfile" }}-2_3_5

  rspec-2_2_8:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.2.8-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: gems-{{ checksum "Gemfile" }}-2_2_8
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
      - save_cache:
          paths:
            - vendor/bundle
          key: gems-{{ checksum "Gemfile" }}-2_2_8

workflows:
  version: 2
  build:
    jobs:
      - lint
      - rspec-2_4_2:
          requires:
            - lint
      - rspec-2_3_5
          requires:
            - lint
      - rspec-2_2_8
          requires:
            - lint
