version: 2

jobs:
  rspec-2_4_2:
    working_directory: ~/tsumamigui
    docker:
      - image: ruby:2.4.2
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-2_4_2
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-2_4_2
          paths:
            - vendor/bundle

workflows:
  version: 2
  build:
    jobs:
      - rspec-2_4_2
