version: 2

jobs:
  rspec-2_4_2:
    working_directory: ~/tsumamigui
    docker:
      - image: circleci/ruby:2.4.2-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-2_4_2
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-2_4_2
          paths:
            - vendor/bundle
      - run: bundle exec rspec

  rspec-2_3_5:
    working_directory: ~/tsumamigui
    docker:
      - image: circleci/ruby:2.3.5-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-2_3_5
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-2_3_5
          paths:
            - vendor/bundle
      - run: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - rspec-2_4_2
      - rspec-2_3_5
